(async()=>{
const $=id=>document.getElementById(id),meta=await fetch('data/meta.json').then(r=>r.json());
const csv=async u=>{const L=(await fetch('data/'+u).then(r=>r.text())).trim().split('\n'),c=L[0].split(','),d={date:[]};c.slice(1).forEach(k=>d[k]=[]);for(let i=1;i<L.length;i++){const p=L[i].split(',');d.date.push(p[0]);for(let j=1;j<p.length;j++)d[c[j]].push(p[j]===''?NaN:+p[j])}return d};
const [R,E]=await Promise.all([csv('book_daily.csv'),csv('exposure_daily.csv')]),N=R.date.length,SL=Object.keys(meta.sleeves),TS=Object.keys(meta.tested);
const M=s=>String(s).replace(/^-/,'−'),pc=(v,d=1)=>v==null?'–':M((v*100).toFixed(d))+'%',sg=(v,d=1)=>v==null?'–':(v>0?'+':'')+M((v*100).toFixed(d))+'%',f2=(v,d=2)=>v==null?'–':M(v.toFixed(d)),s2=(v,d=2)=>v==null?'–':(v>0?'+':'')+M(v.toFixed(d));
const NAME={BOOK:'Book',SPX:'S&P 500',B6040:'60/40 portfolio'};SL.forEach(k=>NAME[k]=meta.sleeves[k].label);TS.forEach(k=>NAME[k]=meta.tested[k].label);
const t=meta.today,rk=meta.risk,F=meta.stats.Full,S5=meta.stats['5Y'],S1=meta.stats['1Y'],liveN=R.date.filter(d=>d>=meta.live_since).length,GR=[...new Set(SL.map(k=>meta.sleeves[k].group))];
$('stamp').textContent=`Data through ${meta.last_date}. Simulated: backtest to ${R.date[N-1-liveN]||meta.last_date}, out of sample from ${meta.live_since} (${liveN} sessions so far). Refreshed ${meta.updated}.`;
document.querySelectorAll('.live').forEach(e=>e.textContent=meta.live_since);
$('kp').innerHTML=[[sg(t.d1,2),'Last session'],[sg(t.mtd),'Month to date'],[sg(t.ytd),'Year to date'],[pc(rk.vol_now),'Volatility, 3 months'],[f2(rk.gross)+'x','Gross exposure'],[f2(rk.net)+'x','Net exposure']].map(v=>`<div><b>${v[0]}</b>${v[1]}</div>`).join('');
const st=meta.state;$('state').textContent=`Next session ${st.next_session}, trading day ${st.day_of_month} of the month, ${st.days_to_month_end} sessions before the last one. Turn of the month: ${st.tom?'on':'off'}. End-of-month Treasuries: ${st.eomt?'on':'off'}. Halloween: in ${st.halloween}. Short volatility: ${st.vrp_on?'on':'off'} (VIX one-month over three-month at ${f2(st.vix_ratio)}).`;
let h='<tr><th>Strategy</th><th class="n">Last</th><th class="n">MTD</th><th class="n">YTD</th><th class="n">Sharpe</th><th class="n">5Y</th><th class="n">1Y</th><th class="n">Max DD</th><th class="n">Corr. S&amp;P</th><th class="n">Alpha</th><th class="n">Risk share</th></tr>';
const row=(k,x,b)=>`<tr${b?' class="total"':''}><td>${b?'<b>Book</b>':NAME[k]}</td><td class="n">${sg(x.d1,2)}</td><td class="n">${sg(x.mtd)}</td><td class="n">${sg(x.ytd)}</td><td class="n">${f2(F[k].sharpe)}</td><td class="n">${f2(S5[k].sharpe)}</td><td class="n">${f2(S1[k].sharpe)}</td><td class="n">${pc(F[k].maxdd)}</td><td class="n">${f2(F[k].corr_spx)}</td><td class="n">${f2(F[k].alpha_ir)}</td><td class="n">${b?'':pc(rk.risk_share[k],0)}</td></tr>`;
h+=row('BOOK',t,true);GR.forEach(g=>{h+=`<tr class="g"><td colspan="11">${g}</td></tr>`;SL.filter(k=>meta.sleeves[k].group===g).forEach(k=>h+=row(k,t.sleeves[k]))});$('st').innerHTML=h;
h='<tr><th>Strategy</th><th>Rule</th><th>Source</th></tr>';GR.forEach(g=>{h+=`<tr class="g"><td colspan="3">${g}</td></tr>`;SL.filter(k=>meta.sleeves[k].group===g).forEach(k=>h+=`<tr><td>${NAME[k]}</td><td>${meta.sleeves[k].rule}</td><td class="t">${meta.sleeves[k].source}</td></tr>`)});$('sl').innerHTML=h;
let win=0;
const nav=(v,a)=>{const o=[];let x=100;for(let i=a;i<N;i++){x*=1+(v[i]===v[i]?v[i]:0);o.push(x)}return o},dd=n=>{let m=0;return n.map(x=>{m=Math.max(m,x);return x/m-1})};
function spark(v,ds){const W=160,H=54,A=12;let lo=Math.min(...v,100),hi=Math.max(...v,100);const T=Math.log;lo=T(lo);hi=T(hi);const pad=(hi-lo)*.08||.01;lo-=pad;hi+=pad;
 const n=v.length,stp=Math.max(1,Math.floor(n/160)),X=i=>W*i/(n-1);let d='';for(let i=0;i<n;i+=stp)d+=(i?'L':'M')+X(i).toFixed(1)+' '+(H*(1-(T(v[i])-lo)/(hi-lo))).toFixed(1);
 const y0=H*(1-(T(100)-lo)/(hi-lo));let ax=`<line x1="0" x2="${W}" y1="${H}" y2="${H}" stroke="#111" stroke-width=".6"/>`;
 const tick=(i,tx,anc)=>{ax+=`<line x1="${X(i)}" x2="${X(i)}" y1="${H}" y2="${H+3}" stroke="#111" stroke-width=".6"/><text x="${X(i)}" y="${H+A-1}" font-size="8.5" fill="#555" text-anchor="${anc}">${tx}</text>`};
 if(n<=300){tick(0,ds[0].slice(0,7),'start');tick(n-1,ds[n-1].slice(0,7),'end')}else{const yrs=[];let last='';ds.forEach((s,i)=>{const y=s.slice(0,4);if(y!==last){if(last)yrs.push([i,y]);last=y}});const k=Math.max(1,Math.ceil(yrs.length/4));yrs.filter((_,q)=>q%k===0).forEach(([i,y])=>{if(X(i)>8&&X(i)<W-8)tick(i,y,'middle')})}
 return `<svg viewBox="0 0 ${W} ${H+A}"><line x1="0" x2="${W}" y1="${y0}" y2="${y0}" stroke="#ccc"/><path d="${d}" fill="none" stroke="#111" stroke-width="1.2"/>${ax}</svg>`}
function perf(){const a=win?Math.max(0,N-win):0,x=R.date.slice(a),lv=x.find(d=>d>=meta.live_since),vl=lv&&x[0]<meta.live_since?[lv]:[];
 const b=nav(R.BOOK,a),s=nav(R.SPX,a),m=nav(R.B6040,a),wk=win===252?'1Y':win===1260?'5Y':'Full';
 Plot.line($('c1'),{x,series:[{name:'Book',y:b,width:1.8,dash:''},{name:'60/40 portfolio',y:m,dash:'5 3',color:'#555'},{name:'S&P 500',y:s,dash:'2 3',color:'#888'}],log:true,dec:0,base:100,vline:vl});
 Plot.line($('c2'),{x,series:[{name:'Book',y:dd(b),width:1.8,dash:''},{name:'60/40 portfolio',y:dd(m),dash:'5 3',color:'#555'},{name:'S&P 500',y:dd(s),dash:'2 3',color:'#888'}],pct:true,zero:true,vline:vl});
 $('g3').innerHTML=SL.map(k=>`<div class="cell" style="cursor:default"><b>${NAME[k]}</b><span class="s">Sharpe ${f2(meta.stats[wk][k].sharpe)}, ${pc(meta.stats[wk][k].ret)} a year</span>${spark(nav(R[k],a),x)}</div>`).join('');
 const ea=win?Math.max(0,E.date.length-win):0,cl=meta.classes.filter(c=>E[c].some(v=>Math.abs(v)>1e-6));Plot.stack($('c4'),{x:E.date.slice(ea),series:cl.map(c=>({name:c,y:E[c].slice(ea)})),total:{name:'Net',y:E.net.slice(ea)},dec:2});
 document.querySelectorAll('#wt button').forEach(e=>e.className=+e.dataset.w===win?'on':'')}
$('wt').addEventListener('click',e=>{if(e.target.tagName==='BUTTON'){win=+e.target.dataset.w;perf()}});
const cols=['ret','vol','sharpe','sortino','maxdd','calmar','skew','hit_m','corr_spx'],hd=['Return','Vol','Sharpe','Sortino','Max DD','Calmar','Skew','Months up','Corr. S&P'],fm=[pc,pc,f2,f2,pc,f2,f2,v=>pc(v,0),f2];
h='<tr><th>Annualised, excess of bills</th>'+hd.map(x=>`<th class="n">${x}</th>`).join('')+'</tr>';
[['Full, simulated','Full'],['Last five years','5Y'],['Last year','1Y'],['Out of sample','Live']].forEach(([lab,w])=>{const S=meta.stats[w]||{};h+=`<tr class="g"><td colspan="10">${lab}${w==='Live'&&!S.BOOK?' <span class="t" style="text-transform:none;letter-spacing:0;font-weight:400">starts '+meta.live_since+', shown after 40 sessions</span>':''}</td></tr>`;
 if(S.BOOK)['BOOK','B6040','SPX'].forEach(k=>{h+=`<tr><td>${k==='BOOK'?'<b>Book</b>':NAME[k]}</td>`+cols.map((c,i)=>`<td class="n">${fm[i](S[k][c])}</td>`).join('')+'</tr>'})});$('pt').innerHTML=h;
const ys=Object.keys(meta.monthly).sort().reverse();$('mt').innerHTML='<tr><th>Year</th>'+['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'].map(m=>`<th>${m}</th>`).join('')+'<th>Year</th><th>60/40</th><th>S&amp;P</th></tr>'+ys.map(y=>`<tr><td>${y}</td>`+[...Array(12)].map((_,i)=>{const v=meta.monthly[y][i+1];return `<td>${v==null?'':M((v*100).toFixed(1))}</td>`}).join('')+`<td><b>${M((meta.yearly.BOOK[y]*100).toFixed(1))}</b></td><td>${M((meta.yearly.B6040[y]*100).toFixed(1))}</td><td>${M((meta.yearly.SPX[y]*100).toFixed(1))}</td></tr>`).join('');
const mx=Math.max(...meta.positions.map(p=>Math.abs(p.w)),.01);
$('ps').innerHTML='<tr><th>Instrument</th><th>Class</th><th class="n">Weight</th><th></th><th class="n">Change</th><th class="n">Overnight</th><th>Held by</th></tr>'+meta.positions.map(p=>`<tr><td>${p.label} <span class="t">${p.t}</span></td><td class="d">${p.cls}</td><td class="n"><b>${Math.abs(p.w)<5e-4?'':f2(p.w)}</b></td><td><span class="bar${p.w<0?' neg':''}" style="width:${Math.round(60*Math.abs(p.w)/mx)}px"></span></td><td class="n">${Math.abs(p.w-p.w_prev)<5e-4?'':s2(p.w-p.w_prev,3)}</td><td class="n">${Math.abs(p.night)<5e-4?'':f2(p.night)}</td><td class="t">${p.drivers.map(d=>NAME[d[0]]+' '+s2(d[1])).join(', ')}</td></tr>`).join('')+`<tr class="total"><td><b>Total</b></td><td></td><td class="n"><b>${f2(rk.net)}</b></td><td></td><td></td><td class="n">${f2(rk.night)}</td><td class="t">long ${f2(rk.long)}, short ${f2(rk.short)}, gross ${f2(rk.gross)}</td></tr>`;
const side=w=>Math.abs(w)<5e-4?'flat':w>0?'long':'short';
$('bl').innerHTML=meta.blotter.length?'<tr><th>Effective</th><th>Instrument</th><th>Action</th><th class="n">Size</th><th class="n">From</th><th class="n">To</th><th>Driven by</th><th></th></tr>'+meta.blotter.slice(0,70).map(b=>`<tr><td class="d">${b.date}${b.nxt?' <b>next</b>':''}</td><td>${b.label} <span class="t">${b.t}</span></td><td>${b.trade>0?'Buy':'Sell'}</td><td class="n">${pc(Math.abs(b.trade),1)}</td><td class="n">${f2(b.w0)}</td><td class="n">${f2(b.w1)}</td><td>${NAME[b.sleeve]}</td><td>${b.flip?'<b>now '+side(b.w1)+'</b>':''}</td></tr>`).join(''):'<tr><td>No trades above the threshold in the last ten sessions.</td></tr>';
let g='<tr><th>Instrument</th><th class="n">12m momentum</th><th class="n">Mom. rank</th><th class="n">Value rank</th><th class="n">Carry</th><th class="n">Spec. z</th><th class="n">Vol</th></tr>';
['Equities','Rates','Commodities','Currencies'].forEach(c=>{g+=`<tr class="g"><td colspan="7">${c}</td></tr>`;meta.board.filter(b=>b.cls===c).forEach(b=>{g+=`<tr><td>${b.label} <span class="t">${b.t}</span></td><td class="n">${Math.abs(b.mom12)>=1?'<b>'+s2(b.mom12,1)+'</b>':s2(b.mom12,1)}</td><td class="n">${b.mom==null?'–':Math.round(b.mom*100)}</td><td class="n">${b.val==null?'–':Math.round(b.val*100)}</td><td class="n">${b.carry==null?'':sg(b.carry,2)}</td><td class="n">${b.cot==null?'':(Math.abs(b.cot)>=2?'<b>'+s2(b.cot,1)+'</b>':s2(b.cot,1))}</td><td class="n">${pc(b.vol,0)}</td></tr>`})});$('sg').innerHTML=g;
const wide=meta.pairs.filter(p=>Math.abs(p.z)>=1.5);
$('mn').innerHTML=`<tr><th>Monitor</th><th>Reading</th></tr><tr><td>VIX curve, one-month over three-month</td><td>${f2(st.vix_ratio)} ${st.vix_ratio<1?'(upward sloping, calm)':'(inverted, stress)'}</td></tr><tr><td>Speculator positioning at extremes, |z| of 2 or more</td><td>${meta.board.filter(b=>b.cot!=null&&Math.abs(b.cot)>=2).map(b=>b.label+' '+s2(b.cot,1)).join(', ')||'none'} <span class="t">CFTC through ${meta.sources.cot_through}</span></td></tr><tr><td>Pairs with a spread of 1.5 standard deviations or more</td><td>${wide.map(p=>p.pair+' '+s2(p.z,1)).join(', ')||'none'}</td></tr>`;
$('rk').innerHTML=[[pc(rk.vol_now),'Volatility, 3 months'],[pc(rk.var95,2),'VaR, 1 day 95%'],[pc(rk.es95,2),'Expected shortfall'],[pc(rk.worst,2),'Worst day, 2 years'],[f2(rk.beta_spx),'Beta to S&P 500'],[f2(rk.beta_ust),'Beta to 7-10y Treasuries']].map(v=>`<div><b>${v[0]}</b>${v[1]}</div>`).join('');
$('rc').innerHTML='<tr><th>Strategy</th><th class="n">Share of risk</th></tr>'+SL.slice().sort((a,b)=>rk.risk_share[b]-rk.risk_share[a]).map(k=>`<tr><td>${NAME[k]}</td><td class="n">${pc(rk.risk_share[k],0)}</td></tr>`).join('');
$('ec').innerHTML='<tr><th>Asset class</th><th class="n">Net exposure</th></tr>'+meta.classes.map(c=>`<tr><td>${c}</td><td class="n">${f2(rk.by_class[c])}x</td></tr>`).join('')+`<tr><td>Equities, overnight only</td><td class="n">${f2(rk.night)}x</td></tr>`;
$('sx').innerHTML='<tr><th>Episode</th><th class="n">Book</th><th class="n">60/40</th><th class="n">S&amp;P 500</th></tr>'+Object.entries(rk.stress).map(([k,v])=>`<tr><td>${k}</td><td class="n"><b>${sg(v.book)}</b></td><td class="n">${sg(v.b6040)}</td><td class="n">${sg(v.spx)}</td></tr>`).join('');
$('cr').innerHTML='<tr><th></th>'+SL.map(k=>`<th>${k}</th>`).join('')+'</tr>'+SL.map((a,i)=>`<tr><td>${NAME[a]} <span class="t">${a}</span></td>`+SL.map((b,j)=>j>i?'<td></td>':`<td>${Math.round(meta.corr[a][b]*100)}</td>`).join('')+'</tr>').join('');
const H=meta.honest,V=meta.versus,C=meta.criteria,sr=F.BOOK.sharpe,np_=C.filter(c=>c.ok).length,nt=Object.keys(meta.trials).length,worse=V.sub.filter(x=>x.book<x.b6040);
$('verdict').innerHTML=`Over the simulated period the book has a Sharpe ratio of <b>${f2(sr)}</b>, against ${f2(V.b6040.sharpe)} for a 60/40 portfolio and ${f2(V.spx.sharpe)} for the S&amp;P 500, with a maximum drawdown of ${pc(F.BOOK.maxdd,0)} against ${pc(V.b6040.maxdd,0)} and ${pc(V.spx.maxdd,0)}. It passes <b>${np_} of ${C.length}</b> criteria. `+(H.dsr<0.8?`The one it fails is the hardest: after ${nt} ideas tried, the probability that its true Sharpe ratio beats what luck alone would produce is ${pc(H.dsr,0)}, below the 80% asked for. `:'')+`The chance that the gain over 60/40 is real is ${pc(V.b6040.p,0)}`+(worse.length?`, and in ${worse.length} of ${V.sub.length} thirds of the sample 60/40 did better`:'')+`. So the simulation is encouraging but not proof. The out-of-sample record from ${meta.live_since} is the test that counts.`;
$('cq').innerHTML='<tr><th>Criterion</th><th class="n">Value</th><th class="n">Result</th></tr>'+C.map((c,i)=>`<tr><td>${c.name}</td><td class="n">${i===4?pc(c.value,0):f2(c.value)}</td><td class="n ${c.ok?'ok':'no'}">${c.ok?'pass':'fail'}</td></tr>`).join('');
$('vs').innerHTML='<tr><th></th><th class="n">Sharpe</th><th class="n">Book minus it</th><th class="n">Chance the gain is real</th><th class="n">90% band</th><th class="n">Max DD</th>'+V.sub.map(x=>`<th class="n">${x.start.slice(0,4)} to ${x.end.slice(0,4)}</th>`).join('')+'</tr>'+
 `<tr class="total"><td><b>Book</b></td><td class="n">${f2(sr)}</td><td></td><td></td><td></td><td class="n">${pc(F.BOOK.maxdd,0)}</td>`+V.sub.map(x=>`<td class="n">${f2(x.book)}</td>`).join('')+'</tr>'+
 [['60/40 portfolio',V.b6040,'b6040'],['S&amp;P 500',V.spx,'spx']].map(([n,v,k])=>`<tr><td>${n}</td><td class="n">${f2(v.sharpe)}</td><td class="n">${s2(v.diff)}</td><td class="n">${pc(v.p,0)}</td><td class="n">${s2(v.lo)} to ${s2(v.hi)}</td><td class="n">${pc(v.maxdd,0)}</td>`+V.sub.map(x=>`<td class="n">${f2(x[k])}</td>`).join('')+'</tr>').join('');
const BS=V.by_start,lose=BS.filter(x=>x.book<x.b6040);
$('bs').innerHTML='<tr><th>Sample starts in</th>'+BS.map(x=>`<th class="n">${x.start}</th>`).join('')+'</tr>'+[['Book','book'],['60/40 portfolio','b6040'],['S&amp;P 500','spx']].map(([n,k])=>`<tr${k==='book'?' class="total"':''}><td>${k==='book'?'<b>Book</b>':n}</td>`+BS.map(x=>`<td class="n">${k==='book'&&x.book>=Math.max(x.b6040,x.spx)?'<b>'+f2(x[k])+'</b>':f2(x[k])}</td>`).join('')+'</tr>').join('');
$('bsn').textContent=lose.length?`It does. The book is ahead of 60/40 when the sample includes 2008 and the years just after, when it avoided the crisis. Starting in ${lose.map(x=>x.start).join(', ')} it is behind or level. Most of its edge over a passive portfolio comes from the first third of the sample.`:'The book is ahead of 60/40 from every starting year shown.';
document.querySelectorAll('.start').forEach(e=>e.textContent=meta.start);
const inb=new Set(SL.map(k=>NAME[k])),why={};TS.forEach(k=>why[NAME[k]]=meta.tested[k].why);
$('tt').innerHTML='<tr><th>Idea</th><th class="n">Sharpe</th><th>Status</th></tr>'+Object.entries(meta.trials).sort((a,b)=>b[1]-a[1]).map(([n,v])=>`<tr><td>${inb.has(n)?'<b>'+n+'</b>':n}</td><td class="n">${f2(v)}</td><td class="t">${inb.has(n)?'in the book':why[n]?'left out: '+why[n].charAt(0).toLowerCase()+why[n].slice(1):'research, not adopted'}</td></tr>`).join('');
perf();
})().catch(e=>{document.getElementById('stamp').textContent='Could not load data: '+e.message});
