(async()=>{
const $=id=>document.getElementById(id),m=await fetch('data/meta.json').then(r=>r.json());
const M=s=>String(s).replace(/^-/,'−'),f=(v,d=2)=>v==null?'–':M(v.toFixed(d)),sg=(v,d=2)=>v==null?'–':(v>0?'+':'')+M(v.toFixed(d));
const FM=m.families,P=m.policy,BN={cpi:'CPI',pce:'PCE'};
let B='cpi',win=120;try{const q=localStorage.getItem('rstar-basis');if(q==='pce'||q==='cpi')B=q}catch(e){}
$('stamp').textContent=`Market data through ${m.as_of}. Refreshed ${m.updated}.`;
const c=m.now.cpi,p=m.now.pce,sc=m.stance.cpi,sp=m.stance.pce;
$('kp').innerHTML=[[f(c.median)+'%','Median r-star, CPI terms'],[f(p.median)+'%','Median r-star, PCE terms'],[f(sc.real_policy)+'%','Real policy rate, CPI'],[f(sp.real_policy)+'%','Real policy rate, PCE'],[sg(sc.gap_median)+' / '+sg(sp.gap_median),'Policy minus median r-star, CPI / PCE'],[f(m.wedge),'Long-run CPI inflation minus PCE']].map(v=>`<div><b>${v[0]}</b>${v[1]}</div>`).join('');
const where=(s,n)=>s.real_policy>n.high?'above every estimate':s.real_policy<n.low?'below every estimate':'inside the range';
$('verdict').textContent=`Measured against CPI the estimates run from ${f(c.low)}% to ${f(c.high)}% with a median of ${f(c.median)}%, and the real policy rate is ${f(sc.real_policy)}%, ${where(sc,c)}. Measured against PCE they run from ${f(p.low)}% to ${f(p.high)}% with a median of ${f(p.median)}%, and the real policy rate is ${f(sp.real_policy)}%, ${where(sp,p)}.`;
$('basisn').textContent=`Inflation-protected Treasuries pay CPI, so market measures are real rates against CPI. The Federal Reserve targets PCE inflation. CPI is expected to run ${f(m.wedge)} points above PCE over the long run, so the same nominal rate is that much lower in real terms against CPI. Every number here is shown on both.`;
$('sk').innerHTML=[[f(P.effr)+'%','Effective federal funds rate, '+P.effr_date],[f(P.target_lo)+' to '+f(P.target_hi),'Target range'],[f(sc.expected_inflation)+'%','Expected CPI inflation, next year'],[f(sp.expected_inflation)+'%','Expected PCE inflation, next year']].map(v=>`<div><b>${v[0]}</b>${v[1]}</div>`).join('');
$('st').innerHTML='<tr><th>Basis</th><th class="n">Expected inflation</th><th class="n">Real policy rate</th><th class="n">Median r-star</th><th class="n">Gap</th><th class="n">Gap against the range</th><th class="n">Nominal neutral</th></tr>'+['cpi','pce'].map(b=>{const s=m.stance[b],n=m.now[b];return `<tr><td>${BN[b]}</td><td class="n">${f(s.expected_inflation)}</td><td class="n"><b>${f(s.real_policy)}</b></td><td class="n">${f(n.median)}</td><td class="n"><b>${sg(s.gap_median)}</b></td><td class="n">${sg(s.gap_low)} to ${sg(s.gap_high)}</td><td class="n">${f(s.nominal_neutral)}</td></tr>`}).join('');
$('stn').textContent=`The real policy rate is the effective federal funds rate minus the inflation expected over the next year, in CPI and in PCE. The gap is the real policy rate minus the median r-star on the same basis: above the range policy restrains, below it policy stimulates, inside it the answer depends on the estimate. Nominal neutral is the median plus long-run expected inflation on that basis (${f(sc.long_run_inflation)}% CPI, ${f(sp.long_run_inflation)}% PCE).`;
const N=m.history.date.length,nz=a=>a.map(v=>v==null?NaN:v);
function spark(v,ds){const W=160,Hh=54,A=12,x=v.filter(z=>z===z);if(!x.length)return'';let lo=Math.min(...x,0),hi=Math.max(...x,0);const pad=(hi-lo)*.08||.1;lo-=pad;hi+=pad;const nn=v.length,X=i=>W*i/(nn-1),Y=z=>Hh*(1-(z-lo)/(hi-lo));let pth='',pen=false;v.forEach((z,i)=>{if(z!==z){pen=false;return}pth+=(pen?'L':'M')+X(i).toFixed(1)+' '+Y(z).toFixed(1);pen=true});
 let ax=`<line x1="0" x2="${W}" y1="${Hh}" y2="${Hh}" stroke="#111" stroke-width=".6"/>`;const yrs=[];let last='';ds.forEach((q,i)=>{const y=q.slice(0,4);if(y!==last){if(last)yrs.push([i,y]);last=y}});const k=Math.max(1,Math.ceil(yrs.length/4));yrs.filter((_,q)=>q%k===0).forEach(([i,y])=>{if(X(i)>8&&X(i)<W-8)ax+=`<line x1="${X(i)}" x2="${X(i)}" y1="${Hh}" y2="${Hh+3}" stroke="#111" stroke-width=".6"/><text x="${X(i)}" y="${Hh+A-1}" font-size="8.5" fill="#555" text-anchor="middle">${y}</text>`});
 return `<svg viewBox="0 0 ${W} ${Hh+A}"><line x1="0" x2="${W}" y1="${Y(0)}" y2="${Y(0)}" stroke="#ccc"/><path d="${pth}" fill="none" stroke="#111" stroke-width="1.2"/>${ax}</svg>`}
function draw(){const n=m.now[B],H=m.history[B],o=B==='cpi'?'pce':'cpi';
 document.querySelectorAll('.bn').forEach(e=>e.textContent=BN[B]);
 let h=`<tr><th>Family</th><th class="n">Estimates</th><th class="n">${BN[B]} terms</th><th class="n">${BN[o]} terms</th><th class="n">1 year ago</th><th class="n">5 years ago</th></tr>`;
 FM.forEach(x=>{h+=`<tr><td>${x.name}</td><td class="n">${x.n}</td><td class="n"><b>${f(x[B])}</b></td><td class="n"><span class="t">${f(x[o])}</span></td><td class="n">${f(x.y1[B])}</td><td class="n">${f(x.y5[B])}</td></tr>`});
 h+=`<tr class="total"><td><b>Median</b> <span class="t">of the ${n.n} estimates</span></td><td class="n">${n.n}</td><td class="n"><b>${f(n.median)}</b></td><td class="n">${f(m.now[o].median)}</td><td class="n">${f(H.median[N-13])}</td><td class="n">${f(H.median[N-61])}</td></tr>`;$('tb').innerHTML=h;
 $('tbn').textContent=`Real rates, percent a year. Each family is shown by the median of its estimates. The 1-year and 5-year columns are in ${BN[B]} terms.`;
 const ord=FM.slice().sort((a,b)=>b[B]-a[B]),top=Math.max(...FM.map(x=>x[B]),.1);
 $('c1').innerHTML='<table>'+ord.map(x=>`<tr><td style="width:34%">${x.name}</td><td style="width:1%" class="n"><b>${f(x[B])}</b></td><td><span style="display:inline-block;height:9px;vertical-align:middle;width:${Math.max(1,Math.round(100*x[B]/top))}%;background:#111"></span></td></tr>`).join('')+`<tr class="total"><td><b>Median of all estimates</b></td><td class="n"><b>${f(n.median)}</b></td><td><span style="display:inline-block;height:9px;vertical-align:middle;width:${Math.max(1,Math.round(100*n.median/top))}%;background:repeating-linear-gradient(90deg,#111 0 3px,#fff 3px 6px)"></span></td></tr></table>`;
 const a=win?Math.max(0,N-win):0,x=m.history.date.slice(a),sl=k=>nz(H[k]).slice(a);
 Plot.line($('c2'),{x,series:[{name:'Median',y:sl('median'),width:1.9,dash:''},{name:'Lowest',y:sl('low'),dash:'2 3',color:'#777'},{name:'Highest',y:sl('high'),dash:'5 3',color:'#777'}],dec:1,zero:true});
 $('g3').innerHTML=FM.map(x2=>`<div class="cell" style="cursor:default"><b>${x2.name}</b><span class="s">${f(x2[B])}%</span>${spark(nz(H.fam[x2.name]).slice(a),x)}</div>`).join('');
 Plot.line($('c4'),{x,series:[{name:'Real policy rate',y:sl('real_policy'),width:1.9,dash:''},{name:'Median r-star',y:sl('median'),dash:'5 3',color:'#444'},{name:'Lowest',y:sl('low'),dash:'1 3',color:'#888'},{name:'Highest',y:sl('high'),dash:'1 3',color:'#888'}],dec:1,zero:true});
 const L=m.bcb;if(L&&L.stats){const q=L.stats[B],q2=L.stats[o];$('bcbn').textContent=`Across ${L.n} measures the US median is ${f(q.median)}% in ${BN[B]} terms (${f(q2.median)}% in ${BN[o]} terms), the mean ${f(q.mean)}% and the interquartile range ${f(q.q25)}% to ${f(q.q75)}%. ${L.note||''}`}
 document.querySelectorAll('#wt button').forEach(e=>e.className=+e.dataset.w===win?'on':'');document.querySelectorAll('.bt button').forEach(e=>e.className=e.dataset.b===B?'on':'')}
$('wt').addEventListener('click',e=>{if(e.target.tagName==='BUTTON'){win=+e.target.dataset.w;draw()}});
document.querySelectorAll('.bt').forEach(t=>t.addEventListener('click',e=>{if(e.target.tagName==='BUTTON'){B=e.target.dataset.b;try{localStorage.setItem('rstar-basis',B)}catch(_){}draw()}}));
draw();
})().catch(e=>{document.getElementById('stamp').textContent='Could not load data: '+e.message});
