(async()=>{
const $=id=>document.getElementById(id),m=await fetch('data/meta.json').then(r=>r.json());
const M=s=>String(s).replace(/^-/,'−'),f=(v,d=2)=>v==null?'n/a':M(v.toFixed(d)),sg=(v,d=2)=>v==null?'n/a':(v>0?'+':'')+M(v.toFixed(d)),pct=(v,d=2)=>v==null?'n/a':f(v,d)+'%';
const MO=['January','February','March','April','May','June','July','August','September','October','November','December'],mn=s=>MO[+s.slice(5,7)-1]+' '+s.slice(0,4),ms=s=>MO[+s.slice(5,7)-1].slice(0,3)+' '+s.slice(2,4);
const dl=s=>{if(!s)return'not yet scheduled';const[y,mo,d]=s.split('-');return (+d)+' '+MO[+mo-1]+' '+y};
const n=m.next,P=m.path,F=P.filter(r=>r.kind==='forecast'),A=P.filter(r=>r.kind==='actual'),e=m.energy;
$('stamp').textContent=`Next release: ${mn(n.month)} CPI on ${dl(n.release)}. Last official print: ${mn(m.last_actual)}. Pump prices through the week of ${e.gasoline_last_week}. Refreshed ${m.updated}.`;
$('nx').textContent=`${mn(n.month)} CPI, to be released on ${dl(n.release)}.`;
$('kp').innerHTML=[[sg(n.headline_mom)+'%','Headline, monthly',`${sg(n.headline_p10)} to ${sg(n.headline_p90)}`],[sg(n.core_mom)+'%','Core, monthly',`${sg(n.core_p10)} to ${sg(n.core_p90)}`],[pct(n.headline_yoy),'Headline, 12 months',''],[pct(n.core_yoy),'Core, 12 months','']].map(v=>`<div><b>${v[0]}</b>${v[1]}${v[2]?'<br><span class="t">80% range '+v[2]+'</span>':''}</div>`).join('');
$('stale').textContent=`Official data through ${mn(m.last_actual)}. Energy prices as of ${m.today}.`;
$('ct').innerHTML='<tr><th>Contribution to the monthly change</th><th class="n">Change</th><th class="n">Contribution, pp</th></tr>'+
 `<tr><td>Core (all items less food and energy)</td><td class="n">${sg(n.core_mom)}%</td><td class="n">${sg(n.contrib_core,3)}</td></tr><tr><td>Food</td><td class="n">${sg(n.food_mom)}%</td><td class="n">${sg(n.contrib_food,3)}</td></tr><tr><td>Energy</td><td class="n"></td><td class="n">${sg(n.contrib_energy,3)}</td></tr><tr><td>&nbsp;&nbsp;of which gasoline</td><td class="n">${sg(n.gasoline_mom_sa,1)}%</td><td class="n">${sg(n.contrib_gasoline,3)}</td></tr><tr class="total"><td><b>Headline</b></td><td class="n"><b>${sg(n.headline_mom)}%</b></td><td class="n"><b>${sg(n.headline_mom,3)}</b></td></tr>`;
const H=m.history;if(H.length>=3)Plot.line($('c1'),{x:H.map(r=>r.run_date),series:[{name:'Headline',y:H.map(r=>r.headline_mom),width:1.8,dash:''},{name:'Core',y:H.map(r=>r.core_mom),dash:'5 3',color:'#555'}],dec:2});
else $('c1').innerHTML=`<p class="note">The chart appears after three daily readings. First reading for this print: ${H[0].run_date}, headline ${sg(H[0].headline_mom)}%, core ${sg(H[0].core_mom)}%.</p>`;
$('ek').innerHTML=[['$'+f(e.gasoline_last,3),'Pump price, week of '+e.gasoline_last_week],['$'+f(n.gasoline_price,3),'Monthly average, '+ms(n.month)],].map(v=>`<div><b>${v[0]}</b>${v[1]}</div>`).join('');
const G=await fetch('data/gasoline_weekly.csv').then(r=>r.text()).then(t=>t.trim().split('\n').slice(1).map(l=>l.split(','))),gl=G.filter(r=>r[2]==='0').pop()[0];
Plot.line($('c2'),{x:G.map(r=>r[0]),series:[{name:'Pump price',y:G.map(r=>+r[1]),width:1.8,dash:''}],dec:2,vline:[gl],xfmt:s=>s,legend:false});
$('et').innerHTML='<tr><th>Month</th><th class="n">Average pump price</th><th class="n">Observed</th><th class="n">CPI gasoline, monthly</th><th class="n">Effect on headline, pp</th></tr>'+F.map(r=>`<tr><td>${mn(r.month)}</td><td class="n">$${f(r.gasoline_price,3)}</td><td class="n">${r.gasoline_weeks_observed} of ${r.gasoline_weeks} weeks</td><td class="n">${sg(r.gasoline_mom_sa,1)}%</td><td class="n">${sg(r.contrib_gasoline,3)}</td></tr>`).join('');
const ye=m.year_end,yk=Object.keys(ye).filter(k=>ye[k]);
$('yk').innerHTML=yk.flatMap(y=>[[pct(ye[y].headline),'Headline, December '+y],[pct(ye[y].core),'Core, December '+y]]).map(v=>`<div><b>${v[0]}</b>${v[1]}, 12 months</div>`).join('');
{const ya=m.year_average||{},en=m.year_end_energy,yl=yk[yk.length-1],t=[];
const av=Object.keys(ya).filter(k=>ya[k]).map(y=>`${y} on average over ${y-1}: headline ${pct(ya[y].headline,1)}, core ${pct(ya[y].core,1)}`);
if(av.length)t.push('<b>Calendar-year averages.</b> '+av.join('. ')+'. The December rate compares two single months, so it swings with whatever energy did a year earlier; the average is the steadier number.');
if(en&&en.baseline&&en.as_priced&&en.unchanged&&yl){const lo=en.as_priced.gasoline<en.unchanged.gasoline?en.as_priced:en.unchanged,hi=lo===en.as_priced?en.unchanged:en.as_priced;
t.push(`<b>How much rides on energy.</b> The path has gasoline at $${f(en.baseline.gasoline)} a gallon in December ${yl}. At $${f(lo.gasoline)} headline would end ${yl} at ${pct(lo.headline,1)}; at $${f(hi.gasoline)}, at ${pct(hi.headline,1)}. Core is ${pct(ye[yl].core,1)} in all three.`);}
$('ykn').innerHTML=t.join('<br>');}
const X=P.filter(r=>r.kind!=='not published'||true),x=X.map(r=>r.month),v0=F[0].month;
Plot.line($('c3'),{x,series:[{name:'Headline',y:X.map(r=>r.headline_yoy==null?NaN:r.headline_yoy),width:1.8,dash:''},{name:'Core',y:X.map(r=>r.core_yoy==null?NaN:r.core_yoy),dash:'5 3',color:'#555'}],dec:1,vline:[v0],xfmt:ms});
Plot.line($('c4'),{x,series:[{name:'Headline',y:X.map(r=>r.headline_mom==null?NaN:r.headline_mom),width:1.6,dash:''},{name:'Core',y:X.map(r=>r.core_mom==null?NaN:r.core_mom),dash:'5 3',color:'#555'}],dec:2,zero:true,vline:[v0],xfmt:ms});
const rows=[...A.slice(-6),...F];
$('pt').innerHTML='<tr><th>Month</th><th>Release</th><th class="n">Headline, monthly</th><th class="n">Core, monthly</th><th class="n">Headline, 12 months</th><th class="n">Core, 12 months</th><th></th></tr>'+rows.map(r=>`<tr${r.month===n.month?' class="total"':''}><td>${r.month===n.month?'<b>'+mn(r.month)+'</b>':mn(r.month)}</td><td class="d">${r.kind==='actual'?(r.release||''):dl(r.release)}</td><td class="n">${sg(r.headline_mom)}</td><td class="n">${sg(r.core_mom)}</td><td class="n">${f(r.headline_yoy)}</td><td class="n">${f(r.core_yoy)}</td><td class="t">${r.kind==='actual'?'official':'forecast'}</td></tr>`).join('');
$('ptn').textContent='Monthly changes are seasonally adjusted, 12-month rates are not. The BLS published no index for October 2025, so the lines break there and the 12-month rate for October 2026 cannot be computed.';
const cal=m.calendar.filter(c=>c[0]>=m.last_actual),sched=new Set(m.calendar.map(c=>c[0]));
$('cl').innerHTML='<tr><th>Reference month</th><th>Release date</th><th class="n">Headline, monthly</th><th class="n">Core, monthly</th></tr>'+[...cal.map(c=>({k:c[0],d:c[1]})),...F.filter(r=>!sched.has(r.month)).slice(0,4).map(r=>({k:r.month,d:null}))].map(c=>{const r=P.find(q=>q.month===c.k)||{};return `<tr><td>${mn(c.k)}</td><td>${c.d?dl(c.d):'<span class="t">not yet scheduled by the BLS</span>'}</td><td class="n">${sg(r.headline_mom)}${r.kind==='actual'?' <span class="t">official</span>':''}</td><td class="n">${sg(r.core_mom)}</td></tr>`}).join('');
const sc=m.scored;
$('rc').innerHTML=sc.length?'<tr><th>Print</th><th>Call as of</th><th class="n">Headline call</th><th class="n">Actual</th><th class="n">Miss, bp</th><th class="n">Core call</th><th class="n">Actual</th><th class="n">Miss, bp</th></tr>'+sc.map(s=>`<tr><td>${mn(s.month)}</td><td class="d">${s.as_of}</td><td class="n">${sg(s.headline_forecast)}</td><td class="n">${sg(s.headline_actual)}</td><td class="n">${sg((s.headline_actual-s.headline_forecast)*100,0)}</td><td class="n">${sg(s.core_forecast)}</td><td class="n">${sg(s.core_actual)}</td><td class="n">${sg((s.core_actual-s.core_forecast)*100,0)}</td></tr>`).join(''):'<tr><td>No print has been scored yet.</td></tr>';
$('rcn').textContent=sc.length?'Each call is the last one made before the release. Misses are actual minus call, in basis points of the monthly change.':`The record starts with the ${mn(n.month)} print. Each call is frozen the day before its release and compared with the official number.`;
})().catch(e=>{document.getElementById('stamp').textContent='Could not load data: '+e.message});
